- hosts: all
  vars:
    vhosts:
      - { name: example.com, docroot: /var/www/example.com/htdocs }
      - { name: example.net, docroot: /var/www/example.net/htdocs }
      - { name: example.org, docroot: /var/www/example.org/htdocs }
  tasks:
    - name: generate Apache vhost config file
      template:
        src: vhost.conf2.j2
        dest: /home/ansible/vhost.conf2
