- hosts: all
  vars:
    vhosts:
      - { name: example.com, isauth: false, docroot: /var/www/example.com/htdocs }
      - { name: example.net, isauth: true, docroot: /var/www/example.net/htdocs }
      - { name: example.org, isauth: false, docroot: /var/www/example.org/htdocs }
  tasks:
    - name: generate Apache vhost config file
      template:
        src: vhost.conf3.j2
        dest: /home/ansible/vhost.conf3
